name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Log in to GitHub Packages
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and tag the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/cell-sight-package:latest
        docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/cell-sight-package:latest ghcr.io/${{ github.repository_owner }}/cell-sight-package:latest
        
    - name: Push the Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cell-sight-package:latest
      
    - name: Push the Docker image to GitHub Packages
      run: docker push ghcr.io/${{ github.repository_owner }}/cell-sight-package:latest
